<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Общие-выводы." data-toc-modified-id="Общие-выводы.-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Общие выводы.</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

Подключим необходимые бибилиотеки.

In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')

Загрузим и изучим данные. Удалим полные дубликаты при их наличии.

In [2]:
data = pd.read_csv('/datasets/insurance.csv')
print(data.head())
data = data.drop_duplicates()
print(data.shape)
data.info()

display(data.corr())
print(np.linalg.det(data.corr()))

   Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0
(4847, 5)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 4847 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                4847 non-null   int64  
 1   Возраст            4847 non-null   float64
 2   Зарплата           4847 non-null   float64
 3   Члены семьи        4847 non-null   int64  
 4   Страховые выплаты  4847 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 227.2 KB


Пол   Возраст  Зарплата  Члены семьи  \
Пол                1.000000  0.001953  0.015456    -0.007315   
Возраст            0.001953  1.000000 -0.017386    -0.009064   
Зарплата           0.015456 -0.017386  1.000000    -0.031687   
Члены семьи       -0.007315 -0.009064 -0.031687     1.000000   
Страховые выплаты  0.011565  0.654964 -0.013123    -0.039303   

                   Страховые выплаты  
Пол                         0.011565  
Возраст                     0.654964  
Зарплата                   -0.013123  
Члены семьи                -0.039303  
Страховые выплаты           1.000000

0.5688370474878363


Удалилось 153 полных дубликата из 5000, это около 3%, что является допустимым. Видно, что есть 4 различных признака и 1 целевое значение. Типы данных и названия признаков корректны. Также проверим корреляцию признаков, так как при мультиколлениарности в модели регрессии, становится трудно или невозможно разделить влияние регрессоров на зависимую переменную. В итоге модель может оказаться неадекватной. Построим матрицу корреляции. И найдем ее определитель. Видно, что все коэффициенты корреляции в модуле меньше 0.7, что говорит об отсутствии мультиколлениарности. Кроме того, определитель корреляционной матрицы далек от 0, значит сильной связи между регрессорами нет.

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

Необходимо ответить на следующий вопрос:
"Признаки умножают на обратимую матрицу. Изменится ли качество линейной регрессии? (Её можно обучить заново.)"


**Ответ:** Не изменится. 

**Обоснование:** 

Формулы для раскрытия скобок:
1. для невыражденных квадратных матрицу
$$
(AB)^{-1} = B^{-1}A^{-1} 
$$
2. 
$$
(AB)^{T} = B^{T}A^{T}
$$
Таким образом, 
$$
a = Xw = X(X^T X)^{-1} X^T y 
$$
Пусть 
$$
Z = XP
$$
, где P - обратимая матрица, тогда


$$
a_1 = XPw_1 = XP((XP)^T XP)^{-1} (XP)^T y = XP(P^{T}X^{T}XP)^{-1}P^{T}X^{T}y
$$

$$
X^{T}XP 
$$

является квадратной матрицей, поэтому можно примернить свойство обратных матриц:

$$
XP(P^{T}X^{T}XP)^{-1}P^{T}X^{T}y = XP(X^{T}XP)^{-1}(P^{T})^{-1}P^{T}X^{T}y
$$

$$
(P^{T})^{-1}P^{T} = E
$$

Поэтому

$$
XP(X^{T}XP)^{-1}(P^{T})^{-1}P^{T}X^{T}y = XP(X^{T}XP)^{-1}X^{T}y = XPP^{-1}(X^{T}X)^{-1}X^{T}y = XPP^{-1}(X^{T}X)^{-1}X^{T}y = X(X^{T}X)^{-1}X^{T}y
$$

$$
a_1 = a_0
$$

Доказано, что результат предсказаний одинаков.

Как связаны параметры линейной регрессии в исходной задаче и в преобразованной?

$$
w_1 = (X^{T}XP)^{-1}(P^{T})^{-1}P^{T}X^{T}y = (X^{T}XP)^{-1}X^{T}y = P^{-1}(X^{T}X)^{-1}X^{T}y = P^{-1}(X^{T}X)^{-1}X^{T}y = P^{-1}w
$$

Таким образом, $$w_1 = P^{-1}w$$

Ответ: параметры $w$ и $w_p$ можно выразить друг через друга так: $$w_1 = P^{-1}w$$

## Алгоритм преобразования

**Алгоритм**

1. Раздеяем данные на признаки и целевые значения.
2. Генерируем случайную квадратную матрицу размером равным количеству признаков.
3. Проверяем эту матрицу на обратимость. (Она должна быть обратимой, ее определитель не равен 0). Если матрица необратима, генерируем новую до тех пор, пока она не пройдет проверку на обратимость.
4. Находим новую матрицу признаков путем умножения исходной на полученную на предыдущем этапе алгоритма.
5. Обучаем модель и находим пресказания с новой матрицей.

**Обоснование**

Качество линейной регрессии не поменяется, так как в пункте 2 было доказано, что перемножение матрицы признаков на обратимую матрицу не влияет на предсказание. При этом обратимая матрица должна иметь размер, равный количеству признаков, иначе мы не сможем выполнить умножение. При этом обратимая матрица каждый раз будет определяться случайным образом, что позволит закодировать исходные данные без влияния на конечный результат.

## Проверка алгоритма

Разделим выборку.

In [3]:
X = data.drop("Страховые выплаты", axis=1)
y = data["Страховые выплаты"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=12345)

Обучим модель на исходных данных и посчитаем метрику r2.

In [4]:
model = LinearRegression()
model.fit(X_train,y_train)
prediction = model.predict(X_train)
print(r2_score(y_train, prediction))

0.43215820285832096


В цикле найдем обратимую матрицу, подходящего для матрицы признаков размера. В цикле же проверим ее на обратимость и будем генерировать случайную матрицу до момента, пока не получим ту, которая удовлетваоряет условию. При этом вероятность получить случайную матрицу с определителем равным 0 крайне мала. Но тем не менее. Далее умножим на эту матрицу исходную, заново обучим модель, уже на этой матрице и снова найдем r2. Если в обоих случаях r2 будут равны, это будет служить подтверждением доказательства из п.2. и верностью алгоритма из п.3

In [5]:
i = 0
while i != 1:
    R = np.random.random(size=(X_train.shape[1],X_train.shape[1]))
    if np.linalg.det(R) != 0:
        A = R
        i = 1
print(A)

X_1 = X_train @ A
model.fit(X_1,y_train)
prediction = model.predict(X_1)
print(r2_score(y_train, prediction))

[[0.80710932 0.07486981 0.45498945 0.50150802]
 [0.0904915  0.92515552 0.63900113 0.21999026]
 [0.17377922 0.02283448 0.86458021 0.34725579]
 [0.64121604 0.01400044 0.81884013 0.97861685]]
0.43215820285832685


Видно, что r2 равны или максимально близки. Таким образом, задача решается верно.

## Общие выводы.
1. Нами были и загружены и изучены данные. Удалены дубликаты, проведена проверка на мультиколлениарность. Проверены типы ланных.
2. Было доказано, что качество линейной регрессии на искходной матрице не изменяется, если умножить исходную матрицу на любую квадратную обратимую.
3. Был предложен алгоритм преобразования данных.
4. Алгоритм преобразования данных был запрограммирован, после чего была проверена метрика R2 для данных без преобразования и с преобразованием. Стало очевидно, что метрика одинакова, что соответствует доказательству из 2 пункта.
    
  

## Чек-лист проверки

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [x]  Весь код выполняется без ошибок
- [x]  Ячейки с кодом расположены в порядке исполнения
- [x]  Выполнен шаг 1: данные загружены
- [x]  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [x]  Указан правильный вариант ответа
    - [x]  Вариант обоснован
- [x]  Выполнен шаг 3: предложен алгоритм преобразования
    - [x]  Алгоритм описан
    - [x]  Алгоритм обоснован
- [x]  Выполнен шаг 4: алгоритм проверен
    - [x]  Алгоритм реализован
    - [x]  Проведено сравнение качества моделей до и после преобразования